In [1]:
import numpy as np
import sys
from scipy.optimize import minimize

#Enter basic variables, non basic variables and the inital simplex method in standard form
#Can use 'simplex test input' txt file for prewritten input from past assignments and also input for written project just copy & paste 

#2.2 1st simplex method example problem
basic = np.array(['w1', 'w2'])
nonbasic = np.array(['x1', 'x2', 'w1', 'w2'])
A = np.array([[-4.0,-3.0,0.0,0.0,0.0], [1.0,1.0,1.0,0.0,40.0],
              [2.0,1.0,0.0,1.0,60.0]])

Z_Row = [ele[:-1] for ele in A] 

print("NOTE: " +   "\n"
      "This code abides by the specifications of the assignment which states to " + "\n"
      " - Use Python to run the problem and determine the optimal solution. " + "\n"
      " - The initial simplex matrix that you entered into the Python program" + "\n"
      " - The final simplex matrix given by the computer program")
print("INITIAL SIMPLEX:")
print(A)
print('--------------------------------------------------------------')
while((Z_Row[0] < 0).any()):
 #   entering_number = A[0][0];
  #  for col in range(0, len(A[0])):
   #     if (A[0][col] < entering_number):    
  #          entering_number = A[0][col];
    old_smallest_col = np.argmin(A[0])
    entering_variable = nonbasic[np.argmin(Z_Row[0])]
    print("entering variable: " + str(entering_variable))
    curr_smallest = 100000
    prev_smallest = curr_smallest;
    for row in range(1, len(A)):
        curr_smallest = A[row][len(A[0])-1]/A[row][np.argmin(A[0])];
        if (curr_smallest < prev_smallest and A[row][np.argmin(A[0])] != 0 and curr_smallest >=0):
            prev_smallest = curr_smallest;
            index = row;
    unbound = 0
    for row in range(1, len(A)):
        if (A[row][np.argmin(A[0])] < 0):
            unbound = unbound + 1
    if(unbound == (len(A)-1)):
        print("UNBOUNDED")
        sys.exit()
    print("smallest number after dividing is: " + str(prev_smallest) + " this corresponds with row: " + str(index))
    exiting_variable = basic[index - 1]
    print("exiting variable: " + str(exiting_variable))
    basic[index - 1] = nonbasic[np.argmin(A[0])]
    print("Basic variables: " + str(basic))
    print("Nonbasic variables: " + str(nonbasic))
    print('--------------------------------------------------------------')
    print("Divide pivot row by pivot value: ")
    for col in range(0, len(A[0])):
        A[index] = (A[index]/A[index][np.argmin(A[0])])
    print(A)
    print('--------------------------------------------------------------')
    print("Zero out the rest of the pivot column and implement proper row operations: ")
    for row in range(0, index):
        if(A[row][np.argmin(A[0])] != 0):
            A[row] = (A[row] - (A[row][old_smallest_col]*A[index][old_smallest_col])*A[index])
    for row in range(index+1, len(A)):
        if(A[row][old_smallest_col] != 0):
            A[row] = (A[row] - (A[row][old_smallest_col]*A[index][old_smallest_col])*A[index])
    print(A)
    print('--------------------------------------------------------------')
    print("REPEAT UNTIL ALL VALUES IN THE OBJECTIVE ROW ARE NON NEGATIVE")
    print('--------------------------------------------------------------')
    
print("FINAL SIMPLEX:")
print(A)
print('--------------------------------------------------------------')
print("Basic variables: " + str(basic))
print("Nonbasic variables: " + str(nonbasic))
print("OPTIMAL SOLUTION:")
print("Z = " + str(A[0][len(A[0])-1]))

NOTE: 
This code abides by the specifications of the assignment which states to 
 - Use Python to run the problem and determine the optimal solution. 
 - The initial simplex matrix that you entered into the Python program
 - The final simplex matrix given by the computer program
INITIAL SIMPLEX:
[[-4. -3.  0.  0.  0.]
 [ 1.  1.  1.  0. 40.]
 [ 2.  1.  0.  1. 60.]]
--------------------------------------------------------------
entering variable: x1
smallest number after dividing is: 30.0 this corresponds with row: 2
exiting variable: w2
Basic variables: ['w1' 'x1']
Nonbasic variables: ['x1' 'x2' 'w1' 'w2']
--------------------------------------------------------------
Divide pivot row by pivot value: 
[[-4.  -3.   0.   0.   0. ]
 [ 1.   1.   1.   0.  40. ]
 [ 1.   0.5  0.   0.5 30. ]]
--------------------------------------------------------------
Zero out the rest of the pivot column and implement proper row operations: 
[[  0.   -1.    0.    2.  120. ]
 [  0.    0.5   1.   -0.5  10. ]
